### ISSUE TITLE
to_dvorak.py fails with AttributeError

### ISSUE THREAD

**Issue by seren** [wimglenn/pycharm-dvorak-keymap#2]
Hi, thanks for the nice utility. The current version is throwing an error:

`Traceback (most recent call last):`
`File "to_dvorak.py", line 102, in <module>`
`main(fname=args.infile, outfname=args.outfile)`
`File "to_dvorak.py", line 59, in main`
`for node in soup.component.keymap.descendants:`
`AttributeError: 'NoneType' object has no attribute 'keymap'`

This seems to be due to using `soup.component.keymap` instead of `soup.keymap`. I'll submit a PR shortly.

**Comment by wimglenn** [comment]
Hi Seren, glad it was useful for you.  I merged your changes, cheers.
